### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Hexstream** [Shinmera/kandria#2]
I'm surprised I can't seem to find a license for Kandria, especially for a project of such scope and your level of experience and investment in it. Has this been decided yet?

As always, I strongly recommend [the Unlicense](https://unlicense.org/), but MIT or similar is also great, just not as great. ;P

**Comment by Shinmera** [comment]
The lack of a license is intentional for the time being.

**Comment by Hexstream** [comment]
Thanks, but I really hope this will be fully open-source, as it would automatically make it a much better vehicle for promoting Common Lisp.
