### ISSUE TITLE
New velocity system bug for animations

### ISSUE THREAD

**Issue by brobbeh** [Shinmera/kandria#4]
The new velocity looks good but there seems to be some bug on how it gets activated. If you do light ground 3 combo it ll work fine the first time, but if you do it again (without moving in between) it will have no speed at all. Moving around a bit resets it work fine again, I just cant do it more than once in a row without the bug happening.

**Comment by Shinmera** [comment]
So you mean just mashing left click to trigger the bug, or leftleftleft (pause) leftleftleft?

**Comment by brobbeh** [comment]
Just keep doing left click to reproduce the bug.
________________________________
De : Nicolas Hafner <notifications@github.com>
Envoyé : jeudi 26 novembre 2020 15:12
À : Shinmera/kandria <kandria@noreply.github.com>
Cc : brobbeh <b_l__o_b@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Shinmera/kandria] New velocity system bug for animations (#4)


So you mean just mashing left click to trigger the bug, or leftleftleft (pause) leftleftleft?

**Comment by brobbeh** [comment]
ACtually i mean click 3 times to trigger the anim, let it reset to stand anim then click 3 times again to go back to light ground 3
________________________________
De : frederic tarabout <b_l__o_b@hotmail.com>
Envoyé : jeudi 26 novembre 2020 15:19
À : Shinmera/kandria <reply@reply.github.com>
Objet : RE: [Shinmera/kandria] New velocity system bug for animations (#4)

Just keep doing left click to reproduce the bug.
________________________________
De : Nicolas Hafner <notifications@github.com>
Envoyé : jeudi 26 novembre 2020 15:12
À : Shinmera/kandria <kandria@noreply.github.com>
Cc : brobbeh <b_l__o_b@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Shinmera/kandria] New velocity system bug for animations (#4)


So you mean just mashing left click to trigger the bug, or leftleftleft (pause) leftleftleft?

**Comment by brobbeh** [comment]
I had not realized you can maintain the last stage by spamming until now!
________________________________
De : frederic tarabout <b_l__o_b@hotmail.com>
Envoyé : jeudi 26 novembre 2020 15:20
À : Shinmera/kandria <reply@reply.github.com>
Objet : RE: [Shinmera/kandria] New velocity system bug for animations (#4)

ACtually i mean click 3 times to trigger the anim, let it reset to stand anim then click 3 times again to go back to light ground 3
________________________________
De : frederic tarabout <b_l__o_b@hotmail.com>
Envoyé : jeudi 26 novembre 2020 15:19
À : Shinmera/kandria <reply@reply.github.com>
Objet : RE: [Shinmera/kandria] New velocity system bug for animations (#4)

Just keep doing left click to reproduce the bug.
________________________________
De : Nicolas Hafner <notifications@github.com>
Envoyé : jeudi 26 novembre 2020 15:12
À : Shinmera/kandria <kandria@noreply.github.com>
Cc : brobbeh <b_l__o_b@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Shinmera/kandria] New velocity system bug for animations (#4)


So you mean just mashing left click to trigger the bug, or leftleftleft (pause) leftleftleft?

**Comment by Shinmera** [comment]
I can't always reproduce what you're seeing, but sometimes it does not accelerate forward as much as it should. What the hell.
